#!/usr/bin/env python
#
# ***** BEGIN GPL LICENSE BLOCK *****
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# The Original Code is Copyright (C) 2015, Blender Foundation
# All rights reserved.
#
# The Original Code is: all of this file.
#
# Contributor(s): Kevin Dietrich
#
# ***** END GPL LICENSE BLOCK *****

Import ('env')

sources = []

defs = []
incs = [
    '.',
    'intern',
    env['BF_GLEW_INC']
]

incs = ' '.join(incs)

if env['WITH_BF_OPENVDB']:
    defs.append('WITH_OPENVDB')

    incs += ' ' + env['BF_BOOST_INC']
    incs += ' ' + env['BF_OPENEXR_INC']
    incs += ' ' + env['BF_OPENVDB_INC']

    sources = env.Glob('*.cc') + env.Glob('intern/*.cc')

env.BlenderLib ( libname = 'bf_intern_openvdb', sources = sources, includes = Split(incs), defines = defs, libtype=['core'], priority = [364] )
